In [57]:
import numpy as np
import pandas as pd
from sys import getsizeof
from config import *
from tqdm import tqdm
from sklearn.model_selection import train_test_split

<pre>
Numpy: 無法確定 index 就是 user, item's id
Pandas: 計算時使用 numpy，資料結構依賴 Pandas
</pre>

* filter: > 3 interactions
* create matrix
* train test split
* train valid split

In [58]:
def filter_interaction(df_inter):
    print('origin shape: ', df_inter.shape)
    vc_user = df_inter['user_id'].value_counts()
    mask = df_inter['user_id'].isin(vc_user[vc_user >= 3].index)
    df_inter = df_inter.loc[mask].reset_index(drop=True)
    print('> 3 interactions: ', df_inter.shape)
    return df_inter

## douban

In [59]:
'''
一定得先取出 user, item 的 unique，再去切分 train test。
'''

df_inter = pd.read_csv(data_path_douban + 'user_book.dat', sep='\t', header=None).rename({
    0: 'user_id',
    1: 'item_id',
    2: 'rating',
}, axis=1)

# index - 1
df_inter['user_id'], df_inter['item_id'] = df_inter['user_id'] - 1, df_inter['item_id'] - 1
ls_user_unique = df_inter['user_id'].unique()
ls_item_unique = df_inter['item_id'].unique()
ls_user_unique.sort()
ls_item_unique.sort()

df_inter = filter_interaction(df_inter)
print(ls_user_unique[-10:], ', unique: ', len(ls_user_unique))
print(ls_item_unique[-10:], ', unique: ', len(ls_item_unique))

df_train_inter, df_test_inter = train_test_split(df_inter, test_size=0.2, shuffle=True, random_state=RANDOM_STATE)
df_train_inter, df_test_inter = df_train_inter.reset_index(drop=True), df_test_inter.reset_index(drop=True)

df_train_inter.to_csv(data_preprocessing + 'douban_train_interaction.csv', index=False)
df_train_inter.to_csv(data_preprocessing + 'douban_test_interaction.csv', index=False)
np.save(data_preprocessing + 'douban_user_unique', ls_user_unique)
np.save(data_preprocessing + 'douban_item_unique', ls_item_unique)

origin shape:  (792062, 3)
> 3 interactions:  (790197, 3)
[13014 13015 13016 13017 13018 13019 13020 13021 13022 13023] , unique:  13024
[22337 22338 22339 22340 22341 22342 22343 22344 22345 22346] , unique:  22347


## movie_lens

In [60]:
'''
一定得先取出 user, item 的 unique，再去切分 train test。
'''

df_inter = pd.read_csv(data_path_movie + 'user_movie.dat', sep='\t', header=None).rename({
    0: 'user_id',
    1: 'item_id',
    2: 'rating',
}, axis=1)

# index - 1
df_inter['user_id'], df_inter['item_id'] = df_inter['user_id'] - 1, df_inter['item_id'] - 1
ls_user_unique = df_inter['user_id'].unique()
ls_item_unique = df_inter['item_id'].unique()
ls_user_unique.sort()
ls_item_unique.sort()

df_inter = filter_interaction(df_inter)
print(ls_user_unique[-10:], ', unique: ', len(ls_user_unique))
print(ls_item_unique[-10:], ', unique: ', len(ls_item_unique))

df_train_inter, df_test_inter = train_test_split(df_inter, test_size=0.2, shuffle=True, random_state=RANDOM_STATE)
df_train_inter, df_test_inter = df_train_inter.reset_index(drop=True), df_test_inter.reset_index(drop=True)

df_train_inter.to_csv(data_preprocessing + 'movielen_train_interaction.csv', index=False)
df_train_inter.to_csv(data_preprocessing + 'movielen_test_interaction.csv', index=False)
np.save(data_preprocessing + 'movielen_user_unique', ls_user_unique)
np.save(data_preprocessing + 'movielen_item_unique', ls_item_unique)

origin shape:  (100000, 4)
> 3 interactions:  (100000, 4)
[933 934 935 936 937 938 939 940 941 942] , unique:  943
[1672 1673 1674 1675 1676 1677 1678 1679 1680 1681] , unique:  1682


## Yelp

In [61]:
'''
一定得先取出 user, item 的 unique，再去切分 train test。
'''

df_inter = pd.read_csv(data_path_yelp + 'user_business.dat', sep='\t', header=None).rename({
    0: 'user_id',
    1: 'item_id',
    2: 'rating',
}, axis=1)

# index - 1
df_inter['user_id'], df_inter['item_id'] = df_inter['user_id'] - 1, df_inter['item_id'] - 1
ls_user_unique = df_inter['user_id'].unique()
ls_item_unique = df_inter['item_id'].unique()
ls_user_unique.sort()
ls_item_unique.sort()

df_inter = filter_interaction(df_inter)
print(ls_user_unique[-10:], ', unique: ', len(ls_user_unique))
print(ls_item_unique[-10:], ', unique: ', len(ls_item_unique))

df_train_inter, df_test_inter = train_test_split(df_inter, test_size=0.2, shuffle=True, random_state=RANDOM_STATE)
df_train_inter, df_test_inter = df_train_inter.reset_index(drop=True), df_test_inter.reset_index(drop=True)

df_train_inter.to_csv(data_preprocessing + 'yelp_train_interaction.csv', index=False)
df_train_inter.to_csv(data_preprocessing + 'yelp_test_interaction.csv', index=False)
np.save(data_preprocessing + 'yelp_user_unique', ls_user_unique)
np.save(data_preprocessing + 'yelp_item_unique', ls_item_unique)

origin shape:  (198397, 3)
> 3 interactions:  (188456, 3)
[16229 16230 16231 16232 16233 16234 16235 16236 16237 16238] , unique:  16239
[14274 14275 14276 14277 14278 14279 14280 14281 14282 14283] , unique:  14284
